name: build k3-merlin.ng

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
#  branches: 
#    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/godcong/asuswrt-merlin.ng 
        echo $(pwd)
        
        
        cd asuswrt-merlin.ng/release/src/router/
        git clone --depth=1 https://github.com/godcong/k3screenctrl 
               
    - name: Build Firmware
      run: |
        cd asuswrt-merlin.ng/release/src-rt-7.14.114.x/src
        make rt-k3
        sudo mv -f asuswrt-merlin.ng/release/src-rt-7.14.114.x/src/image/*.trx /opt/images/
