name: build k3-merlin.ng

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
#  branches: 
#    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-16.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      uses: actions/checkout@master
      # Runs a single command using the runners shell
    - name: update && install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y libncurses5 libncurses5-dev m4 bison gawk flex libstdc++6-4.7-dev g++-4.7 g++ \
        gengetopt git gitk zlib1g-dev autoconf autopoint libtool-bin shtool autogen \
        mtd-utils intltool sharutils docbook-xsl-* libstdc++5 texinfo dos2unix xsltproc \
        u-boot-tools device-tree-compiler qemu gperf liblzo2-dev uuid-dev build-essential \
        lzma-dev liblzma-dev lzma binutils-dev patch cmake intltool libglib2.0-dev \
        gtk-doc-tools
     #   sudo apt-get install -y libtool-bin cmake libproxy-dev uuid-dev liblzo2-dev autoconf automake bash bison \
     #   bzip2 diffutils file flex m4 g++ gawk groff-base libncurses-dev libtool libslang2 make patch perl pkg-config shtool \
     #   subversion tar texinfo zlib1g zlib1g-dev git-core gettext libexpat1-dev libssl-dev cvs gperf unzip \
     #   python libxml-parser-perl gcc-multilib gconf-editor libxml2-dev g++-multilib gitk libncurses5 mtd-utils \
     #   libncurses5-dev libvorbis-dev git autopoint autogen sed build-essential intltool libelf1:i386 libglib2.0-dev \
     #   xutils-dev lib32z1-dev lib32stdc++6 xsltproc gtk-doc-tools
     #   sudo apt-get install -y lib32z1-dev lib32stdc++6
       
     # Runs a set of commands using the runners shell
    - name: update x86 package
      run: |
        sudo dpkg --add-architecture i386
        sudo dpkg --print-foreign-architectures
        sudo apt-get update
        sudo apt-get install -y libc6-i386 lib32stdc++6 lib32z1 libelf1:i386 lib32ncurses5 libc6-dev-i386 
        
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/godcong/asuswrt-merlin.ng 
        echo $(pwd)
          
        cd asuswrt-merlin.ng/release/src/router/
        git clone --depth=1 https://github.com/godcong/k3screenctrl 
               
    - name: Build Firmware
      run: |
        cd asuswrt-merlin.ng/release/src-rt-7.14.114.x/src
        make rt-k3
        
        mkdir -p /opt/images/
        sudo mv -f asuswrt-merlin.ng/release/src-rt-7.14.114.x/src/image/*.trx /opt/images/
